OPENSCAD ?= arch -x86_64 openscad
PYTHON   ?= python3
SCAD      = dual_wedge_charging_dock.scad
# Extra flags, e.g. OPENSCAD_FLAGS='--backend=manifold' on 2024+ snapshots
OPENSCAD_FLAGS ?=
BED = 256

STYLES = soft_monolith floating_deck faceted furniture
# Printable chassis parts, one file per style
PARTS  = base top_plate top_insert
# Style-independent parts
COMMON = dowel_pins fit_test fit_test_mat

STL_STYLED = $(foreach s,$(STYLES),$(foreach p,$(PARTS),$(s)_$(p).stl))
STL_COMMON = $(foreach p,$(COMMON),$(p).stl)
STL_ALL    = $(STL_STYLED) $(STL_COMMON)
MF_ALL     = $(STL_ALL:.stl=.3mf)

.PHONY: all stl 3mf check dimensions debug fit-test clean version help

all: stl 3mf DIMENSIONS.md

stl: $(STL_ALL)
3mf: $(MF_ALL)

version:
	$(OPENSCAD) --version

# --- styled parts: <style>_<part>.{stl,3mf} ---------------------------------
# part name maps to the OpenSCAD `part` variable; top_insert exports flat.
define STYLED_RULE
$(1)_base.stl: $(SCAD)
	$$(OPENSCAD) $$(OPENSCAD_FLAGS) -D 'style="$(1)"' -D 'part="base"' -o $$@ $$<
$(1)_top_plate.stl: $(SCAD)
	$$(OPENSCAD) $$(OPENSCAD_FLAGS) -D 'style="$(1)"' -D 'part="top_plate"' -o $$@ $$<
$(1)_top_insert.stl: $(SCAD)
	$$(OPENSCAD) $$(OPENSCAD_FLAGS) -D 'style="$(1)"' -D 'part="top_insert_flat"' -o $$@ $$<
$(1)_base.3mf: $(SCAD)
	$$(OPENSCAD) $$(OPENSCAD_FLAGS) -D 'style="$(1)"' -D 'part="base"' -o $$@ $$<
$(1)_top_plate.3mf: $(SCAD)
	$$(OPENSCAD) $$(OPENSCAD_FLAGS) -D 'style="$(1)"' -D 'part="top_plate"' -o $$@ $$<
$(1)_top_insert.3mf: $(SCAD)
	$$(OPENSCAD) $$(OPENSCAD_FLAGS) -D 'style="$(1)"' -D 'part="top_insert_flat"' -o $$@ $$<
endef
$(foreach s,$(STYLES),$(eval $(call STYLED_RULE,$(s))))

# --- common parts (rendered with the default style) --------------------------
dowel_pins.stl dowel_pins.3mf: $(SCAD)
	$(OPENSCAD) $(OPENSCAD_FLAGS) -D 'part="dowel_pins"' -o $@ $<
fit_test.stl fit_test.3mf: $(SCAD)
	$(OPENSCAD) $(OPENSCAD_FLAGS) -D 'part="fit_test"' -o $@ $<
fit_test_mat.stl fit_test_mat.3mf: $(SCAD)
	$(OPENSCAD) $(OPENSCAD_FLAGS) -D 'part="fit_test_mat"' -o $@ $<

fit-test: fit_test.stl fit_test_mat.stl

# Debug / reference geometry (never printed)
debug: fit_dummies.stl cable_clearance.stl
fit_dummies.stl: $(SCAD)
	$(OPENSCAD) $(OPENSCAD_FLAGS) -D 'part="fit_dummies"' -o $@ $<
cable_clearance.stl: $(SCAD)
	$(OPENSCAD) $(OPENSCAD_FLAGS) -D 'part="cable_clearance"' -o $@ $<

# --- validation ---------------------------------------------------------------
# Renders every part (asserts run for every style) and verifies each mesh is
# watertight, consistently oriented and fits the bed.
check: $(STL_ALL)
	@for s in $(STYLES); do \
	  $(OPENSCAD) $(OPENSCAD_FLAGS) -D "style=\"$$s\"" -D 'part="dimensions"' -o /tmp/dock_dims_$$s.stl $(SCAD) 2>&1 | grep -q 'DIM|Style' \
	    || { echo "asserts failed for style $$s"; exit 1; }; \
	done
	$(PYTHON) check_mesh.py --bed $(BED) $(STL_ALL)
	@echo "check: all parts watertight, manifold and within $(BED) mm"

# Dimension table generated from the model so README cannot drift.
DIMENSIONS.md: $(SCAD) Makefile
	@echo "# Dimensions (generated by \`make dimensions\`, do not edit)" > $@
	@echo "" >> $@
	@for s in $(STYLES); do \
	  echo "## $$s" >> $@; echo "" >> $@; \
	  echo "| Item | Value |" >> $@; echo "|---|---|" >> $@; \
	  $(OPENSCAD) $(OPENSCAD_FLAGS) -D "style=\"$$s\"" -D 'part="dimensions"' -o /tmp/dock_dims_$$s.stl $(SCAD) 2>&1 \
	    | sed -n 's/^ECHO: "DIM|\([^|]*\)|\(.*\)"$$/| \1 | \2 |/p' >> $@; \
	  echo "" >> $@; \
	done
	@echo "wrote $@"

dimensions: DIMENSIONS.md

clean:
	rm -f $(STL_ALL) $(MF_ALL) fit_dummies.stl cable_clearance.stl DIMENSIONS.md

help:
	@echo "make            render every STL and 3MF plus DIMENSIONS.md"
	@echo "make check      render everything and verify meshes (watertight, manifold, on bed)"
	@echo "make fit-test   10-minute fit coupons (PETG + TPU)"
	@echo "make <style>_<part>.stl   e.g. make soft_monolith_top_plate.stl"
	@echo "styles: $(STYLES)   parts: $(PARTS)"
